### ISSUE TITLE
Not able connect cassandra using Spark

### ISSUE THREAD

**Issue by madhest** [tuplejump/calliope-release#13]
# getting the following error:

14/06/21 19:00:15 INFO TaskSetManager: Serialized task 0.0:1 as 2143 bytes in 1 ms
14/06/21 19:00:15 WARN TaskSetManager: Lost TID 0 (task 0.0:0)
14/06/21 19:00:15 WARN TaskSetManager: Loss was due to java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/codehaus/jackson/annotate/JsonClass
    at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector.findDeserializationType(JacksonAnnotationIntrospector.java:524)
    at org.codehaus.jackson.map.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:732)
    at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createCollectionDeserializer(BasicDeserializerFactory.java:229)
    at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:386)
    at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:307)
    at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:287)
    at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:136)
    at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:157)
    at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2468)
    at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2402)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1602)
    at org.apache.cassandra.utils.FBUtilities.fromJsonList(FBUtilities.java:564)
    at org.apache.cassandra.hadoop.cql3.CqlPagingRecordReader.retrieveKeys(CqlPagingRecordReader.java:688)
    at org.apache.cassandra.hadoop.cql3.CqlPagingRecordReader.initialize(CqlPagingRecordReader.java:158)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:113)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:99)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:61)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:262)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:229)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:111)
    at org.apache.spark.scheduler.Task.run(Task.scala:51)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
14/06/21 19:00:16 INFO AppClient$ClientActor: Executor updated: app-20140621185935-0039/0 is now FAILED (Command exited with code 50)
14/06/21 19:00:17 INFO SparkDeploySchedulerBackend: Executor app-20140621185935-0039/0 removed: Command exited with code 50
# Code:

object CassandraCQLTest {

  def main(args: Array[String]){ 
    //val sparkConf = new SparkConf().setAppName("CQLTestApp")
     val sc = new SparkContext("spark://10.234.60.249:7077", "Simple Job",
      System.getenv("SPARK_HOME"))
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/simple-project_2.10-1.0.jar")
    //val sc = new SparkContext(sparkConf)
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/calliope_2.10-0.9.0-U1-C2-EA.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/cassandra-all-2.0.8.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/cassandra-thrift-2.0.4.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/libthrift-0.9.1.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/cassandra-driver-core-1.0.3.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/hadoop-client-2.2.0.jar")
     sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/jackson-all-1.8.2.jar")
      sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/jackson-mapper-asl-1.0.0.jar")
       sc.addJar("/home/pcs/spark_install/spark-1.0.0-bin-hadoop1/examples/jars/jackson-core-asl-1.0.0.jar")

```
val cHost: String = "10.234.31.211"
val cPort: String = "9160"
val KeySpace = "retail"
val InputColumnFamily = "ordercf"
val OutputColumnFamily = "salecount"

val job = new Job()
job.setInputFormatClass(classOf[CqlPagingInputFormat])
ConfigHelper.setInputInitialAddress(job.getConfiguration(), cHost)
ConfigHelper.setInputRpcPort(job.getConfiguration(), cPort)
ConfigHelper.setInputColumnFamily(job.getConfiguration(), KeySpace, InputColumnFamily)
ConfigHelper.setInputPartitioner(job.getConfiguration(), "Murmur3Partitioner")
CqlConfigHelper.setInputCQLPageRowSize(job.getConfiguration(), "3")
```

**Comment by sonyjv** [comment]
@madhest
I also faced a similar issue. Please refer  #15 for the work around.

**Comment by milliondreams** [comment]
It has become a common issue with Spark against different JSON versions. One trick is to drop jackson-core-asl-1.8.8.jar in your _Spark_ classpath.

**Comment by bohemia420** [comment]
@milliondreams 
HeyI have been struggling for 2 days to get rid of this issue but failed. 
Did you mean --jars /root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar,/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-mapper-asl-1.8.8.jar while spark-submit. 

Even this isnt working. If this is so common an issue,it wd be great if you could kindly kindly fix this, I can share the dependencies, too.as in my pom.xml.

**Comment by bohemia420** [comment]
@milliondreams 
HeyI have been struggling for 2 days to get rid of this issue but failed. 
Did you mean --jars /root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar,/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-mapper-asl-1.8.8.jar while spark-submit. 

Even this isnt working. If this is so common an issue,it wd be great if you could kindly kindly fix this, I can share the dependencies, too.as in my pom.xml.

**Comment by bohemia420** [comment]
@milliondreams 
it finally worked, i was using dependency 1.6.1 spark streaming, but running against spark 1.1.0 :) .. it has worked now once I downloaded the 1.6.1 build against hadoop 2.6... PS : I have bigger problems now :D
