### ISSUE TITLE
SparkException: unread block data

### ISSUE THREAD

**Issue by abh1nav** [tuplejump/calliope-release#6]
Running a count operation on a CQL3 table using:

``` scala
val sc = new SparkContext(master, "TestApp")
val cas = CasBuilder.cql3.withColumnFamily("testKeySpace", "mytable")
              .onHost("cassandra1")
              .onPort("9160")
              .patitionedUsing(CasPartitioners.RandomPartitioner)
val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)
val rows = rdd.collect().toList
Console.println(s"The size of the table is: ${rows.length}")
sc.stop()
```

Throws a:

```
WARNING: Loss was due to java.lang.IllegalStateException
java.lang.IllegalStateException: unread block data
        at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2399)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1359)
        at java.io.ObjectInputStream.skipCustomData(ObjectInputStream.java:1934)
        at java.io.ObjectInputStream.readExternalData(ObjectInputStream.java:1827)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1773)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1327)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:349)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:40)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:62)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$run$1.apply$mcV$sp(Executor.scala:195)
        at org.apache.spark.deploy.SparkHadoopUtil.runAsUser(SparkHadoopUtil.scala:49)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
```

Running on:
JVM 1.6.0_45-b06 
Apache Cassandra 1.2.6
Scala 2.10.3
SBT 0.13.1
Spark 0.9.0
calliope 0.9.0-U1-EA

Any help would be appreciated.

**Comment by milliondreams** [comment]
@abh1nav 

We are not able to reproduce this locally or even connecting to remote Cassandra cluster. From our past experience this happens if you end up with different versions of Spark or User code on your master and/or one of the worker nodes. 

Can you please give us more information,
1. What is the mode you are running for Spark, I am assuming you are using Spark Standalone.
2. How are you adding the calliope dependencies to Spark and workers?

Apart from this -

Can you upgrade Java to 1.7.x? 
We don't use 1.6.x anywhere and build Calliope against 1.7 so that may cause issues.

Can you upgrade Cassandra to > 1.2.14?
Quite a few issues in Cassandra were solved between 1.2.6 - 1.2.14

**Comment by abh1nav** [comment]
@milliondreams 
Thanks Rohit - I'll try this again after your suggested Cassandra and Java upgrades and report back.

To answer your questions:
1. Spark was running in cluster mode
2. Calliope was included as an sbt dependency in the driver program

Should I have called `sc.addJar()` to provide the Calliope jars to Spark from within the driver program?

**Comment by milliondreams** [comment]
@abh1nav 

Yes you will need to add the calliope jars and it's dependencies to the workers using **addJar** or bundle them as part of your application jar.

**Comment by ra2085** [comment]
I was getting the same exception. Almost the same cofiguration from "abh1nav" except I'm running on dataxtax 4.0 distro and jvm 7. Can confirm that if you want to start the spark context on a cluster master (spark://master:port) and to use the calliope library, then you must use addJar on at least:

sc.addJar("/path/to/calliope_2.10-0.9.0-U1-C2-EA.jar")
sc.addJar("/path/to/cassandra-all-2.0.5.jar")
sc.addJar("/path/to/cassandra-thrift-2.0.4.jar")
sc.addJar("/path/to/libthrift-0.9.1.jar")

Aso, you must add any other 3rd. party library (including yours) that you're using on your code.

I'm curious, Does SparkConf().setJars(SparkContext.jarOfObject(this)) can help reduce all this hassle?

**Comment by abh1nav** [comment]
@milliondreams @ra2085 I managed to get it all sorted out thanks to your addJar tips. Thanks a bunch for your help :)

Cheers,
--Abhi

**Comment by abh1nav** [comment]
@milliondreams 
I may have been a bit hasty with that last comment. The job now completes 25 of 1272 tasks before crashing with the same `unread block data` error.

Here's the new setup:
JVM 1.7.0_51-b13
Cassandra 1.2.15.1

And, I've made all the updates to the code by providing cassandra, thrift, calliope and a fat jar of my code to the SparkContext.

Here's the relevant stack trace:

```
Apr 03, 2014 12:42:23 AM org.apache.spark.Logging$class logInfo                                                                                                                                          [327/1921]
INFO: Finished TID 19 in 24745 ms on cass6 (progress: 24/1272)
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Completed ResultTask(0, 19)
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Starting task 0.0:65 as TID 65 on executor 4: cass4 (PROCESS_LOCAL)
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Serialized task 0.0:65 as 2175 bytes in 1 ms
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Starting task 0.0:66 as TID 66 on executor 0: cass5 (PROCESS_LOCAL)
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Serialized task 0.0:66 as 2139 bytes in 0 ms
Apr 03, 2014 12:42:31 AM org.apache.spark.Logging$class logInfo
INFO: Finished TID 2 in 32522 ms on cass4 (progress: 25/1272)
Apr 03, 2014 12:42:34 AM akka.event.slf4j.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1 apply$mcV$sp
SEVERE: AssociationError [akka.tcp://spark@cass1:51565] <- [akka.tcp://sparkExecutor@cass5:40115]: Error [unread block data] [
java.lang.IllegalStateException: unread block data
        at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2421)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1382)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:136)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at akka.serialization.JavaSerializer.fromBinary(Serializer.scala:136)
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104)
        at scala.util.Try$.apply(Try.scala:161)
        at akka.serialization.Serialization.deserialize(Serialization.scala:98)
        at akka.remote.serialization.MessageContainerSerializer.fromBinary(MessageContainerSerializer.scala:58)
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104)
        at scala.util.Try$.apply(Try.scala:161)
        at akka.serialization.Serialization.deserialize(Serialization.scala:98)
        at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:23)
        at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:55)
        at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:55)
        at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:73)
        at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:764)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
]
Apr 03, 2014 12:42:34 AM akka.event.slf4j.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1 apply$mcV$sp
SEVERE: AssociationError [akka.tcp://spark@cass1:51565] -> [akka.tcp://sparkExecutor@cass5:40115]: Error [Invalid address: akka.tcp://sparkExecutor@cass5:40115] [
akka.remote.InvalidAssociation: Invalid address: akka.tcp://sparkExecutor@cass5:40115
Caused by: akka.remote.transport.Transport$InvalidAssociationException: cass5: Name or service not known
]
```

**Comment by ra2085** [comment]
Any other changes on your code besides the multiple addJar? Also, would be way easier to manage your code if you use transformers to map your cassandra entities.

**Comment by milliondreams** [comment]
@abh1nav 
Would it be possible for you to share the CQL3 Schema and some sample data. We will try it out here.

In case we are not able to reproduce it, let us get on a call/hangout/skype and see if we can debug it in your environment together.

**Comment by abh1nav** [comment]
@ra2085 No other changes besides the addJar. I wasn't using transformers because I was simply trying to test a basic operation to see if it everything works as expected.

@milliondreams Here's the create statement for the table:

``` SQL
CREATE TABLE log (
  id text,
  points int,
  parentid text,
  PRIMARY KEY (id)
);
```

If you're not able to reproduce it, I'm happy to jump on a call and do a screen share.

Thanks!

**Comment by milliondreams** [comment]
@abh1nav 

Had a couple of overloaded days... so couldn't give this another try. So this is just a look at the above table.

You have an **int** (points) in the table and you are trying to get the output as Map[String, String], Map[String, String] which uses an implicit transformer present in RichByteBuffer.

As @ra2085 mentioned you should try it using a transformer.

For a case class **log**, defined as,

``` scala
case class Log(id: String, points: String, parentId: String)
```

The transformer will be,

``` scala
implicit def cas2Log(k: Map[String, ByteBuffer], v: Map[String, ByteBuffer]) = Log(k("id"), v("points"), v("parentid"))
```

I hope that will solve the issue.

**Comment by abh1nav** [comment]
@milliondreams 
Hi Rohit,

Finally gave this a shot, but I'm still running into the unread block data issue. I've further simplified the table and used a transformer.

Here's what the table looks like:

```
CREATE TABLE points_timestamp (
  id text,
  timestamp text,
  PRIMARY KEY (id)
);
```

And here's the job code:

``` scala
package com.crowdriff.lion.jobs

import com.tuplejump.calliope.{CasPartitioners, CasBuilder}
import com.tuplejump.calliope.Implicits._
import com.tuplejump.calliope.utils.RichByteBuffer._
import java.nio.ByteBuffer
import org.apache.spark.{SparkConf, SparkContext}

object SparkTest {

  val master = "spark://cass1:7077"
  case class LogEntry(id: String, timestamp: String)
  implicit def cql3toLogEntry(k: Map[String, ByteBuffer], v: Map[String, ByteBuffer]) = LogEntry(k("id"), v("timestamp"))

  def run(): Unit = {
    val sconf = new SparkConf().setMaster(master).setAppName("Score Size").set("spark.executor.memory", "16g")
    val sc = new SparkContext(sconf)
    sc.addJar("http://repo1.maven.org/maven2/org/apache/cassandra/cassandra-all/1.2.12/cassandra-all-1.2.12.jar")
    sc.addJar("http://repo1.maven.org/maven2/org/apache/cassandra/cassandra-thrift/1.2.12/cassandra-thrift-1.2.12.jar")
    sc.addJar("http://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.7.0/libthrift-0.7.0.jar")
    sc.addJar("https://oss.sonatype.org/service/local/repositories/releases/content/com/tuplejump/calliope_2.10/0.9.0-U1-EA/calliope_2.10-0.9.0-U1-EA.jar")
    sc.addJar("http://cass1:8000/lion.jar")

    val cas = CasBuilder.cql3.withColumnFamily("hercules", "points_timestamp")
              .onHost("cass1")
              .onPort("9160")
              .patitionedUsing(CasPartitioners.RandomPartitioner)

    val rdd = sc.cql3Cassandra[LogEntry](cas)
    val counters = rdd.collect().toList
    Console.println(s"The size of the points_timestamp collection is: ${counters.length}")
    sc.stop()
  }
}
```

The error is the same one as before,

```
SEVERE: AssociationError [akka.tcp://spark@cass1:33593] <- [akka.tcp://sparkExecutor@cass3:60105]: Error [unread block data] [
java.lang.IllegalStateException: unread block data
        at java.io.ObjectInputStream$BlockDataInputStream.setBlockDataMode(ObjectInputStream.java:2421)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1382)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:136)
        ...
```

**Comment by abh1nav** [comment]
Turns out the issue was this statement:

``` scala
val counters = rdd.collect().toList
```

which, as I now understand, attempts to collect the list and drop it onto the machine running the driver program. The correct way to do what I was trying to do is:

``` scala
val counters = rdd.count()
```

After making this change, everything worked as expected.
Many thanks to @milliondreams for taking the time to help debug this live over screen share.

**Comment by qiaohaijun** [comment]
+1
